services:
  mongo:
    image: mongo
    container_name: estuary-mongodb
    restart: always
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db
    # volumes:
    #   - ${HOME}/dev/data/mongodb:/data/db
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
